---
title: "Feasible sets sampling"
author: "Renata Diaz"
date: "3/25/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)

#import source code that contains the functions necessary to clean the code, generate the macroecological
#patterns, grab the parameters of interest, run the statistical analyses, and to generate the figures used
#in the manuscript.
source("PortalPlants_fxns.R")

```

## get plant data

```{r get data}


# load winter and summer annual plant data and subset out bad data
winter = read.csv("PortalWinterAnnuals_1995_2009.csv")
winter = subset(winter, plot!=1 & plot!=9 & plot!=24)   #omit spectabs removal (1,9) and misshapen plot (24)

summer = read.csv("PortalSummerAnnuals_1995_2009.csv")
summer = subset(summer, plot!=1 & plot!=9 & plot!=24)   #omit spectabs removal (1,9) and misshapen plot (24)

# add spatial areas needed to get averages for SARs
winter_new = add_areas(winter)
summer_new = add_areas(summer)
  summer_new = subset(summer_new, year != 1997 & year != 1998) # yrs where Unid Spp > 10% community
```
  
  
## SADs from data

```{r get SADs}

########## MACROECOLOGICAL PATTERNS ##########
##### The below functions summarize the plant community data, construct the three macroecological patterns,
##### and get the parameters used to characterize each pattern as output for analysis

##### RADs
# reshape data for analysis
winter_wide = reshape_data(winter_new)
summer_wide = reshape_data(summer_new)

#get descriptive parameters for SADs for each plot-year combination
years = c(1995:2009)
winter_rad = RAD_data(winter_wide, years) #returns all the parameters
summer_rad = RAD_data(summer_wide, years) 

str(winter_rad)
str(summer_rad)


```

## Extract real S and Ns

```{r get S and Ns}
winter_y <- winter_rad$year
winter_s <- winter_rad$S
winter_n <- winter_rad$N

summer_y <- summer_rad$year
summer_s <- summer_rad$S
summer_n <- summer_rad$N

winter_sn <- data.frame(year = winter_y, s = winter_s, n = winter_n, season = rep('w', length(winter_y)))
summer_sn <- data.frame(year = summer_y, s = summer_s, n = summer_n,
                        season = rep('s', length(summer_y)))

all_sn <- rbind(winter_sn, summer_sn)

str(all_sn)

unique_sns <- all_sn %>%
  dplyr::select(s, n) %>%
  distinct()

str(unique_sns)

sn_space_plot <- ggplot(data = unique_sns, aes(x = s, y = n)) +
   geom_point(data = unique_sns, aes(x = s, y = n))

min(unique_sns$n)
unique_sns[which(unique_sns$n == 32), 's']

```

How long does it take to get 100 vectors of length 7 that sum to 32?

```{r toy fs function}

get_partition <- function(n ,s){
  
  if(s > n) return(NULL)
  
  sums_correct <- FALSE
  partition <- NULL
  
  while(!sums_correct) {
  partition <- sample.int(n-s+1, size = s, replace = T)
  if(sum(partition) == n) {
    sums_correct <- TRUE
  }
  }
  
  return(sort(partition))

}  

npartitions <- 100
n <- 32
s <- 7
many_partitions <- as.data.frame(t(replicate(npartitions, get_partition(n = n, s = s))))

str(many_partitions)

distinct_partitions <- many_partitions %>%
  distinct()

distinct_partitions

```